name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTIyODc0MzctYjU5YS00Y2VhLWEzMjUtZTZhNGYzMDRmNDExIiwidGVuYW50X2lkIjoiZGVlYTkyZDBkNDI5MGQzZjE2YjI4YTczY2E5MDAwMGI0YmIwNzM1Njg5Y2U5Njc1MTNjMGVhNzE2NmFlMDJhZiIsImludGVybmFsX3NlY3JldCI6ImQ4NTNlNDRmLTM2YTEtNDQyYy1hYTYzLWJhMWU2ZGEzMDVkMiJ9.PmzbyhXxbTpbtVBVxxq0zP7YkXZGMmYbJocG_FCV4Do"
JWT_SECRET="thapa_password"